imports:
    - { resource: config_test.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true

web_profiler:
    toolbar: true

# EightPoints Guzzle
guzzle:
    logging: true
    clients:
        local_test_api:
            base_url: "http://api.rest-user-api.dev/app_acceptance.php/"
#            base_url: "http://127.0.0.1:8000/app_acceptance.php/"




parameters:
    database_name: "db_acceptance"